apiVersion: v1
kind: Service
metadata:
  name: jasmin
spec:
  type: NodePort
  selector:
    app: jasmin
  ports:
    - port: 2775
      protocol: TCP
      targetPort: 2775
      name: smpp
    - port: 8990
      protocol: TCP
      targetPort: 8990
      name: admin
    - port: 1401
      protocol: TCP
      targetPort: 1401
      name: api